// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\r24b_pseudosoftmax_in10_8bit\Final_sub.v
// Created: 2025-09-29 11:51:53
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Final_sub
// Source Path: r24b_pseudosoftmax_in10_8bit/PseudoSM_ASIC/Final_sub
// Hierarchy Level: 1
// Model version: 9.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Final_sub
          (Minus,
           Plus_0,
           Plus_1,
           Plus_2,
           Plus_3,
           Plus_4,
           Plus_5,
           Plus_6,
           Plus_7,
           Plus_8,
           Plus_9,
           Sub_0,
           Sub_1,
           Sub_2,
           Sub_3,
           Sub_4,
           Sub_5,
           Sub_6,
           Sub_7,
           Sub_8,
           Sub_9);


  input   signed [11:0] Minus;  // sfix12
  input   signed [7:0] Plus_0;  // int8
  input   signed [7:0] Plus_1;  // int8
  input   signed [7:0] Plus_2;  // int8
  input   signed [7:0] Plus_3;  // int8
  input   signed [7:0] Plus_4;  // int8
  input   signed [7:0] Plus_5;  // int8
  input   signed [7:0] Plus_6;  // int8
  input   signed [7:0] Plus_7;  // int8
  input   signed [7:0] Plus_8;  // int8
  input   signed [7:0] Plus_9;  // int8
  output  signed [12:0] Sub_0;  // sfix13
  output  signed [12:0] Sub_1;  // sfix13
  output  signed [12:0] Sub_2;  // sfix13
  output  signed [12:0] Sub_3;  // sfix13
  output  signed [12:0] Sub_4;  // sfix13
  output  signed [12:0] Sub_5;  // sfix13
  output  signed [12:0] Sub_6;  // sfix13
  output  signed [12:0] Sub_7;  // sfix13
  output  signed [12:0] Sub_8;  // sfix13
  output  signed [12:0] Sub_9;  // sfix13


  wire signed [7:0] Plus [0:9];  // int8 [10]
  wire signed [12:0] Add_v;  // sfix13
  wire signed [12:0] Add_1 [0:9];  // sfix13 [10]
  wire signed [12:0] Add_out1 [0:9];  // sfix13 [10]


  assign Plus[0] = Plus_0;
  assign Plus[1] = Plus_1;
  assign Plus[2] = Plus_2;
  assign Plus[3] = Plus_3;
  assign Plus[4] = Plus_4;
  assign Plus[5] = Plus_5;
  assign Plus[6] = Plus_6;
  assign Plus[7] = Plus_7;
  assign Plus[8] = Plus_8;
  assign Plus[9] = Plus_9;

  assign Add_v = {Minus[11], Minus};

  genvar t_0_01;
  generate
    for(t_0_01 = 32'sd0; t_0_01 <= 32'sd9; t_0_01 = t_0_01 + 32'sd1) begin:Add_out1_gen
      assign Add_1[t_0_01] = {{5{Plus[t_0_01][7]}}, Plus[t_0_01]};
      assign Add_out1[t_0_01] = Add_1[t_0_01] - Add_v;
    end
  endgenerate

  assign Sub_0 = Add_out1[0];

  assign Sub_1 = Add_out1[1];

  assign Sub_2 = Add_out1[2];

  assign Sub_3 = Add_out1[3];

  assign Sub_4 = Add_out1[4];

  assign Sub_5 = Add_out1[5];

  assign Sub_6 = Add_out1[6];

  assign Sub_7 = Add_out1[7];

  assign Sub_8 = Add_out1[8];

  assign Sub_9 = Add_out1[9];

endmodule  // Final_sub

